chore(pack-images): use debian base

diff --git a/buildpacks/go/bin/build b/buildpacks/go/bin/build
--- a/buildpacks/go/bin/build
+++ b/buildpacks/go/bin/build
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# shellcheck source=/dev/null
+. generate-layer.sh
 set -eo pipefail
 
 echo "---> Go Buildpack"
@@ -10,20 +12,20 @@ plan_path=$3
 # 2. DOWNLOAD go
 go_layer_dir="${layers_dir}/go"
 mkdir -p "${go_layer_dir}"
-arch=$(dpkg --print-architecture)  # amd64 arm64
+arch=$(dpkg --print-architecture) # amd64 arm64
 # determine go version provided during detection
-go_version=$(< "${plan_path}" yj -t | jq -r '.entries[] | select(.name == "go") | .version')
+go_version=$(yj <"${plan_path}" -t | jq -r '.entries[] | select(.name == "go") | .version')
 remote_go_version='not found'
 if [[ -f "${go_layer_dir}.toml" ]]; then
-    remote_go_version=$(< "${go_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_go_version=$(yj <"${go_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
 fi
-if [[ "${go_version}" == "${remote_go_version}" ]] ; then
+if [[ "${go_version}" == "${remote_go_version}" ]]; then
   echo "---> Reusing go"
 else
   echo "---> Downloading and extracting go ${go_version}"
   go_url=https://golang.org/dl/go${go_version}.linux-${arch}.tar.gz
   wget -q -O - "${go_url}" | tar -xzf - -C "${go_layer_dir}"
-  cat > "${go_layer_dir}.toml" <<EOL
+  cat >"${go_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
@@ -40,17 +42,17 @@ export GOPATH="${go_cache_layer_dir}"
 local_mod_checksum=$(sha256sum go.mod | cut -d ' ' -f 1 || echo 'not found')
 remote_mod_checksum='not found'
 if [[ -f "${go_cache_layer_dir}.toml" ]]; then
-    remote_mod_checksum=$(< "${go_cache_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_mod_checksum=$(yj <"${go_cache_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
 fi
 mkdir -p "${go_cache_layer_dir}"
 
-if [[ -f go.mod && "${local_mod_checksum}" == "${remote_mod_checksum}" ]] ; then
+if [[ -f go.mod && "${local_mod_checksum}" == "${remote_mod_checksum}" ]]; then
   echo "---> Reusing go.mod"
 else
   echo "---> Installing go.mod with go mod vendor"
   rm "${go_cache_layer_dir}/pkg" -rf
   go mod download
-  cat > "${go_cache_layer_dir}.toml" <<EOL
+  cat >"${go_cache_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
diff --git a/buildpacks/nodejs/bin/build b/buildpacks/nodejs/bin/build
--- a/buildpacks/nodejs/bin/build
+++ b/buildpacks/nodejs/bin/build
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# shellcheck source=/dev/null
+. generate-layer.sh
 set -eo pipefail
 
 echo "---> Nodejs Buildpack"
@@ -10,24 +12,24 @@ plan_path=$3
 # 2. DOWNLOAD nodejs
 node_layer_dir="${layers_dir}/node"
 mkdir -p "${node_layer_dir}"
-arch=$(dpkg --print-architecture)  # amd64 arm64
+arch=$(dpkg --print-architecture) # amd64 arm64
 if [[ ${arch} == "amd64" ]]; then
-    arch="x64"
+  arch="x64"
 fi
 # determine nodejs version provided during detection
-node_version=$(< "${plan_path}" yj -t | jq -r '.entries[] | select(.name == "nodejs") | .version')
+node_version=$(yj <"${plan_path}" -t | jq -r '.entries[] | select(.name == "nodejs") | .version')
 node_name=node-v${node_version}-linux-${arch}
 remote_node_version='not found'
 if [[ -f "${node_layer_dir}.toml" ]]; then
-    remote_node_version=$(< "${node_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_node_version=$(yj <"${node_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
 fi
-if [[ "${node_version}" == "${remote_node_version}" ]] ; then
+if [[ "${node_version}" == "${remote_node_version}" ]]; then
   echo "---> Reusing Node v${node_version}"
 else
   echo "---> Downloading and extracting Node v${node_version}"
   node_url="https://nodejs.org/dist/v${node_version}/${node_name}.tar.xz"
   wget -q -O - "${node_url}" | tar -xJf - --strip-components=1 -C "${node_layer_dir}"
-  cat > "${node_layer_dir}.toml" <<EOL
+  cat >"${node_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
@@ -38,17 +40,16 @@ fi
 # 3. MAKE node npm AVAILABLE TO THIS SCRIPT
 export PATH="${node_layer_dir}/bin:${PATH}"
 
-
 node_modules_layer_dir="${node_layer_dir}/node_modules"
 mkdir -p "${node_modules_layer_dir}"
 # Compares previous package.json checksum to the current package.json
 local_package_checksum=$(sha256sum package.json | cut -d ' ' -f 1 || echo 'not found')
 remote_package_checksum='not found'
 if [[ -f "${node_modules_layer_dir}.toml" ]]; then
-    remote_package_checksum=$(< "${node_modules_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_package_checksum=$(yj <"${node_modules_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
 fi
 
-if [[ -f package.json && "${local_package_checksum}" == "${remote_package_checksum}" ]] ; then
+if [[ -f package.json && "${local_package_checksum}" == "${remote_package_checksum}" ]]; then
   echo "---> Reusing package.json"
   cp -r "${node_modules_layer_dir}" "./node_modules"
 else
@@ -56,10 +57,10 @@ else
   rm "${node_modules_layer_dir}" -rf
   npm install
   if [[ -d "${node_modules_layer_dir}" ]]; then
-      rm "${node_modules_layer_dir:?}/*" -rf
-			cp -r node_modules/. "${node_modules_layer_dir}/"
+    rm "${node_modules_layer_dir:?}/*" -rf
+    cp -r node_modules/. "${node_modules_layer_dir}/"
   fi
-  cat > "${node_modules_layer_dir}.toml" <<EOL
+  cat >"${node_modules_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
@@ -68,14 +69,14 @@ EOL
 fi
 
 json_get_key() {
-	local file="$1"
-	local key="$2"
+  local file="$1"
+  local key="$2"
 
-	if test -f "$file"; then
-		jq -c -M --raw-output "$key // \"\"" <"$file" || return 1
-	else
-		echo ""
-	fi
+  if test -f "$file"; then
+    jq -c -M --raw-output "$key // \"\"" <"$file" || return 1
+  else
+    echo ""
+  fi
 }
 
 build_script=$(json_get_key "package.json" ".scripts.build")
diff --git a/buildpacks/php/bin/build b/buildpacks/php/bin/build
--- a/buildpacks/php/bin/build
+++ b/buildpacks/php/bin/build
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-
+# shellcheck source=/dev/null
+. generate-layer.sh
 set -eo pipefail
 
 echo "---> PHP Buildpack"
@@ -9,10 +10,10 @@ layers_dir=$1
 plan_path=$3
 
 bp_dir=$(
-	cd "$(dirname "$0")"/..
-	pwd
+  cd "$(dirname "$0")"/..
+  pwd
 )
-arch=$(dpkg --print-architecture)  # amd64 arm64
+arch=$(dpkg --print-architecture) # amd64 arm64
 # 2. DOWNLOAD PHP
 php_layer_dir="${layers_dir}/php"
 mkdir -p "${php_layer_dir}"/config
@@ -20,12 +21,12 @@ extensions_layer_dir="${layers_dir}/extensions"
 mkdir -p "${extensions_layer_dir}"/{docs,ext}
 
 # determine php version provided during detection
-php_version=$(< "${plan_path}" yj -t | jq -r '.entries[] | select(.name == "php") | .version')
+php_version=$(yj <"${plan_path}" -t | jq -r '.entries[] | select(.name == "php") | .version')
 remote_php_version="not found"
 if [[ -f "${php_layer_dir}.toml" ]]; then
-    remote_php_version=$(< "${php_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_php_version=$(yj <"${php_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
 fi
-if [[ "${php_version}" == "${remote_php_version}" ]] ; then
+if [[ "${php_version}" == "${remote_php_version}" ]]; then
   echo "---> Reusing php"
 else
   echo "---> Downloading and extracting php ${php_version} ${arch}"
@@ -36,46 +37,44 @@ else
   "${php_layer_dir}"/bin/php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
   "${php_layer_dir}"/bin/php composer-setup.php --install-dir="${php_layer_dir}/bin/"
   mv "${php_layer_dir}/bin/composer.phar" "${php_layer_dir}/bin/composer"
-  cat > "${php_layer_dir}.toml" <<EOL
+  cat >"${php_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
 metadata = "${php_version}"
 EOL
-if [ ! -s "${php_layer_dir}"/profile.d/php.sh ]; then
-  mkdir "${php_layer_dir}"/profile.d
-  cat > "${php_layer_dir}"/profile.d/php.sh <<EOL
+  if [ ! -s "${php_layer_dir}/profile.d/php.sh" ]; then
+    mkdir "${php_layer_dir}/profile.d"
+    cat >"${php_layer_dir}/profile.d/php.sh" <<EOL
 export PATH="${php_layer_dir}/bin:${php_layer_dir}/sbin:${PATH}"
 export PHP_PEAR_INSTALL_DIR="${php_layer_dir}/lib/php"
 export PHP_PEAR_PHP_BIN="${php_layer_dir}/bin/php"
 export php_layer_dir="${php_layer_dir}"
+export php_version="${php_version}"
 echo "Config pecl"
 pecl config-set php_dir "${php_layer_dir}"
 pecl config-set bin_dir "${php_layer_dir}"/bin
 pecl config-set ext_dir "${php_layer_dir}"/ext
 pecl config-set doc_dir "${extensions_layer_dir}"/docs
 EOL
-fi
-echo "---> Config php-fpm"
-cp -f "${bp_dir}/config/php/"* "${php_layer_dir}/config/"
-cp -f "${bp_dir}"/lib/* "${php_layer_dir}/bin/"
-mv -f "${php_layer_dir}"/bin/Builder.php "${php_layer_dir}"/lib/php/PEAR/Builder.php
+  fi
+  echo "---> Config php-fpm"
+  cp -f "${bp_dir}/config/php/"* "${php_layer_dir}/config/"
+  cp -f "${bp_dir}"/lib/* "${php_layer_dir}/bin/"
+  mv -f "${php_layer_dir}"/bin/Builder.php "${php_layer_dir}"/lib/php/PEAR/Builder.php
 fi
 
 # 3. MAKE PHP AVAILABLE TO THIS SCRIPT
-export PATH="${php_layer_dir}/bin:${php_layer_dir}/sbin:${PATH}"
-export PHP_PEAR_INSTALL_DIR="${php_layer_dir}/lib/php"
-export PHP_PEAR_PHP_BIN="${php_layer_dir}/bin/php"
-export php_layer_dir="${php_layer_dir}"
-export php_version="${php_version}"
+# shellcheck source=/dev/null
+. "${php_layer_dir}/profile.d/php.sh"
 
 # Compares previous extensions.json checksum to the current extensions.json
 local_extensions_checksum="$(sha256sum extensions.json | cut -d ' ' -f 1 || echo 'not found')"
 remote_extensions_checksum="not found"
 if [[ -f "${extensions_layer_dir}.toml" ]]; then
-    remote_extensions_checksum=$(< "${extensions_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_extensions_checksum=$(yj <"${extensions_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
 fi
-if [[ -f extensions.json && "${local_extensions_checksum}" == "${remote_extensions_checksum}" ]] ; then
+if [[ -f extensions.json && "${local_extensions_checksum}" == "${remote_extensions_checksum}" ]]; then
   echo "---> Reusing extensions.json"
 else
   echo "---> Config pecl"
@@ -89,7 +88,7 @@ else
   # shellcheck disable=SC1090
   source "$bp_dir/bin/ext"
   ext_install
-  cat > "${extensions_layer_dir}.toml"<<EOL
+  cat >"${extensions_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
@@ -103,13 +102,13 @@ mkdir -p "${vendor_layer_dir}"
 local_composer_checksum=$(sha256sum composer.json | cut -d ' ' -f 1 || echo 'not found')
 remote_composer_checksum="not found"
 if [[ -f "${vendor_layer_dir}.toml" ]]; then
-    remote_composer_checksum=$(< "${vendor_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_composer_checksum=$(yj <"${vendor_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
 fi
 
 composer config --no-plugins vendor-dir
 composer config --no-plugins bin-dir
 
-if [[ -f composer.json && "${local_composer_checksum}" == "${remote_composer_checksum}" ]] ; then
+if [[ -f composer.json && "${local_composer_checksum}" == "${remote_composer_checksum}" ]]; then
   echo "---> Reusing composer.json"
   cp -r "${vendor_layer_dir}" "./vendor"
 else
@@ -117,9 +116,9 @@ else
   composer install --ignore-platform-reqs
   if [[ -d "${vendor_layer_dir}" ]]; then
     rm "${vendor_layer_dir:?}/*" -rf
-		cp -r vendor/. "${vendor_layer_dir}/"
+    cp -r vendor/. "${vendor_layer_dir}/"
   fi
-  cat > "${vendor_layer_dir}.toml"<<EOL
+  cat >"${vendor_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
@@ -131,26 +130,23 @@ echo "---> Config nginx"
 nginx_layer_dir="${layers_dir}/nginx"
 mkdir -p "${layers_dir}/nginx/"logs
 cp -r /etc/nginx/* "${nginx_layer_dir}"
-cp "${bp_dir}/config/nginx/base.conf" "${nginx_layer_dir}/nginx-php.conf"
-cat > "${nginx_layer_dir}.toml"<<EOL
+cp "${bp_dir}/config/nginx/base.conf" "${nginx_layer_dir}/nginx-php.conf.tpl"
+cat >"${nginx_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
 EOL
 
-cat > "run" <<SH
+cat >"${php_layer_dir}/bin/php-nginx-fpm" <<SH
 #!/usr/bin/env bash
 mkdir -p "${layers_dir}/log" /tmp/nginx/logs/
 touch "${layers_dir}/log/php-fpm.log"
+cat "${nginx_layer_dir}/nginx-php.conf.tpl" > "${nginx_layer_dir}/nginx-php.conf"
+sed -i "s|@ROOT@|\$(readlink -f \$1)|g" "${nginx_layer_dir}/nginx-php.conf"
+sed -i "s|@PORT@|\$2|g" "${nginx_layer_dir}/nginx-php.conf"
 php-fpm -c "${php_layer_dir}/config/php.ini" -y "${php_layer_dir}/config/php-fpm.conf" -p "${php_layer_dir}"
 nginx -p "${nginx_layer_dir}" -c "${nginx_layer_dir}/nginx-php.conf"
 SH
-chmod +x "run"
+chmod +x "${php_layer_dir}/bin/php-nginx-fpm"
 
-echo "---> Generate Launcher"
-
-cat >> "${layers_dir}/launch.toml" <<EOL
-[[processes]]
-type = "web"
-command = "/workspace/run"
-EOL
+generate-launch.sh "${layers_dir}"
diff --git a/buildpacks/rust/bin/build b/buildpacks/rust/bin/build
--- a/buildpacks/rust/bin/build
+++ b/buildpacks/rust/bin/build
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# shellcheck source=/dev/null
+. generate-layer.sh
 set -eo pipefail
 
 echo "---> Rust Buildpack"
@@ -20,13 +22,13 @@ export CARGO_HOME="${rust_layer_dir}"
 RUST_CARGO_BUILD_FLAGS="--release"
 
 # determine rust version provided during detection
-rust_version=$(< "${plan_path}" yj -t | jq -r '.entries[] | select(.name == "rust") | .version')
+rust_version=$(yj <"${plan_path}" -t | jq -r '.entries[] | select(.name == "rust") | .version')
 remote_rust_version="not found"
 if [[ -f "${rust_layer_dir}.toml" ]]; then
-    remote_rust_version=$(< "${rust_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_rust_version=$(yj <"${rust_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
 fi
 
-if [[ "${rust_version}" == "${remote_rust_version}" ]] ; then
+if [[ "${rust_version}" == "${remote_rust_version}" ]]; then
   echo "---> Reusing rustup, checking for new releases of Rust $rust_version channel"
   "${rust_layer_dir}"/bin/rustup self update
   "${rust_layer_dir}"/bin/rustup update "$rust_version"
@@ -35,7 +37,7 @@ else
   # Standard paranoia.
   set -eu
   echo "---> Downloading rustup"
-  curl https://sh.rustup.rs -sSf > rustup.sh
+  curl https://sh.rustup.rs -sSf >rustup.sh
   chmod u+x rustup.sh
   echo "---> Using rustup to install Rust channel ${rust_version}"
   ./rustup.sh -y --default-toolchain "${rust_version}"
@@ -45,7 +47,7 @@ else
     echo "failed: Cannot find Rust binaries at ${rust_layer_dir}"
     exit 1
   fi
-  cat > "${rust_layer_dir}.toml" <<EOL
+  cat >"${rust_layer_dir}.toml" <<EOL
 cache = true
 build = true
 launch = true
@@ -59,7 +61,7 @@ export CARGO_TARGET_DIR="${CARGO_HOME}/target"
 
 echo "-----> Building application using Cargo"
 if [ -s .cargo/config ]; then
-    cp -f .cargo/config "${CARGO_HOME}/config"
+  cp -f .cargo/config "${CARGO_HOME}/config"
 fi
 rm -rf target/
 cargo build $RUST_CARGO_BUILD_FLAGS
