chore(pack-images): change image to drycc base

diff --git a/buildpacks/php/bin/build b/buildpacks/php/bin/build
--- a/buildpacks/php/bin/build
+++ b/buildpacks/php/bin/build
@@ -1,6 +1,4 @@
 #!/usr/bin/env bash
-# shellcheck source=/dev/null
-. generate-layer.sh
 set -eo pipefail
 
 echo "---> PHP Buildpack"
@@ -8,91 +6,62 @@ echo "---> PHP Buildpack"
 # 1. GET ARGS
 layers_dir=$1
 plan_path=$3
+php_layer_dir="${layers_dir}"/php
+extensions_layer_dir="${layers_dir}"/extensions
+mkdir -p "${extensions_layer_dir}"/{docs,ext}
 
 bp_dir=$(
   cd "$(dirname "$0")"/..
   pwd
 )
-arch=$(dpkg --print-architecture) # amd64 arm64
-# 2. DOWNLOAD PHP
-php_layer_dir="${layers_dir}/php"
-mkdir -p "${php_layer_dir}"/config
-extensions_layer_dir="${layers_dir}/extensions"
-mkdir -p "${extensions_layer_dir}"/{docs,ext}
+rm -rf /opt/drycc; ln -s "${layers_dir}" /opt/drycc
 
-# determine php version provided during detection
-php_version=$(yj <"${plan_path}" -t | jq -r '.entries[] | select(.name == "php") | .version')
-remote_php_version="not found"
-if [[ -f "${php_layer_dir}.toml" ]]; then
-  remote_php_version=$(yj <"${php_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
-fi
-if [[ "${php_version}" == "${remote_php_version}" ]]; then
-  echo "---> Reusing php"
-else
-  echo "---> Downloading and extracting php ${php_version} ${arch}"
-  php_url="https://buildpacks.drycc.cc/php/${CNB_STACK_ID}/php-${php_version}-${arch}.tar.gz"
-  wget -q -O - "${php_url}" | tar -xzf - -C "${php_layer_dir}"
-  rm -f "php-${php_version}-${arch}.tar.gz"
-  cp "${php_layer_dir}/sbin/php-fpm" "${php_layer_dir}/bin"
-  "${php_layer_dir}"/bin/php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
-  "${php_layer_dir}"/bin/php composer-setup.php --install-dir="${php_layer_dir}/bin/"
-  mv "${php_layer_dir}/bin/composer.phar" "${php_layer_dir}/bin/composer"
-  cat >"${php_layer_dir}.toml" <<EOL
-cache = true
-build = true
-launch = true
-metadata = "${php_version}"
-EOL
-  if [ ! -s "${php_layer_dir}/profile.d/php.sh" ]; then
-    mkdir "${php_layer_dir}/profile.d"
-    cat >"${php_layer_dir}/profile.d/php.sh" <<EOL
-export PATH="${php_layer_dir}/bin:${php_layer_dir}/sbin:${PATH}"
-export PHP_PEAR_INSTALL_DIR="${php_layer_dir}/lib/php"
-export PHP_PEAR_PHP_BIN="${php_layer_dir}/bin/php"
-export php_layer_dir="${php_layer_dir}"
-export php_version="${php_version}"
-echo "Config pecl"
-pecl config-set php_dir "${php_layer_dir}"
-pecl config-set bin_dir "${php_layer_dir}"/bin
-pecl config-set ext_dir "${php_layer_dir}"/ext
-pecl config-set doc_dir "${extensions_layer_dir}"/docs
-EOL
-  fi
-  echo "---> Config php-fpm"
-  cp -f "${bp_dir}/config/php/"* "${php_layer_dir}/config/"
-  cp -f "${bp_dir}"/lib/* "${php_layer_dir}/bin/"
-  mv -f "${php_layer_dir}"/bin/Builder.php "${php_layer_dir}"/lib/php/PEAR/Builder.php
-fi
-
-# 3. MAKE PHP AVAILABLE TO THIS SCRIPT
+# 2. Install build deps
 # shellcheck source=/dev/null
-. "${php_layer_dir}/profile.d/php.sh"
+. generate-layers.sh "${layers_dir}"
+generate_deps_layer build-deps
+generate_deps_layer run-deps
+
+# 3. install php and nginx
+generate_stack_layer php "${plan_path}" true
+generate_stack_layer nginx "${plan_path}" true
+
+# 4. pre php env and tools
+php_version=$(yj <"${plan_path}" -t | jq -r ".entries[] | select(.name == \"php\") | .metadata.version")
+export php_version="${php_version}"
+export php_layer_dir="${php_layer_dir}"
+mkdir -p "${php_layer_dir}"/config/
+cp -rf "${php_layer_dir}/sbin/php-fpm" "${php_layer_dir}/bin"
+cp -rf "${bp_dir}/config/php/"* "${php_layer_dir}"/config/
+cp -rf "${bp_dir}"/lib/* "${php_layer_dir}"/bin/
+mv -f "${php_layer_dir}"/bin/Builder.php "${php_layer_dir}"/lib/php/PEAR/Builder.php
+# shellcheck source=/dev/null
+. init-stack
 
 # Compares previous extensions.json checksum to the current extensions.json
+pecl config-set ext_dir "${extensions_layer_dir}"/ext
+pecl config-set doc_dir "${extensions_layer_dir}"/docs
+
 local_extensions_checksum="$(sha256sum extensions.json | cut -d ' ' -f 1 || echo 'not found')"
 remote_extensions_checksum="not found"
 if [[ -f "${extensions_layer_dir}.toml" ]]; then
-  remote_extensions_checksum=$(yj <"${extensions_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_extensions_checksum=$(yj <"${extensions_layer_dir}.toml" -t | jq -r .metadata.version 2>/dev/null || echo 'not found')
 fi
 if [[ -f extensions.json && "${local_extensions_checksum}" == "${remote_extensions_checksum}" ]]; then
   echo "---> Reusing extensions.json"
 elif [[ -f extensions.json ]]; then
-  echo "---> Config pecl"
-  pecl config-set php_dir "${php_layer_dir}"
-  pecl config-set bin_dir "${php_layer_dir}"/bin
-  pecl config-set ext_dir "${php_layer_dir}"/ext
-  pecl config-set doc_dir "${extensions_layer_dir}"/docs
   echo "---> Installing extensions.json"
   rm "${php_layer_dir}"/ext/* -rf
   cp -f "${bp_dir}/config/php/php.ini" "${php_layer_dir}/config/"
-  # shellcheck disable=SC1090
-  source "$bp_dir/bin/ext"
-  ext_install
+  "${bp_dir}"/bin/install-extensions
   cat >"${extensions_layer_dir}.toml" <<EOL
+[types]
 cache = true
 build = true
 launch = true
-metadata = "${local_extensions_checksum}"
+
+[metadata]
+version = "${local_extensions_checksum}"
 EOL
 fi
 
@@ -102,7 +71,7 @@ mkdir -p "${vendor_layer_dir}"
 local_composer_checksum=$(sha256sum composer.json | cut -d ' ' -f 1 || echo 'not found')
 remote_composer_checksum="not found"
 if [[ -f "${vendor_layer_dir}.toml" ]]; then
-  remote_composer_checksum=$(yj <"${vendor_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_composer_checksum=$(yj <"${vendor_layer_dir}.toml" -t | jq -r .metadata.version 2>/dev/null || echo 'not found')
 fi
 
 composer config --no-plugins vendor-dir
@@ -119,19 +88,23 @@ else
     cp -r vendor/. "${vendor_layer_dir}/"
   fi
   cat >"${vendor_layer_dir}.toml" <<EOL
+[types]
 cache = true
 build = true
 launch = true
-metadata = "${local_composer_checksum}"
+
+[metadata]
+version = "${local_composer_checksum}"
 EOL
 fi
 
 echo "---> Config nginx"
 nginx_layer_dir="${layers_dir}/nginx"
 mkdir -p "${layers_dir}/nginx/"logs
-cp -r /etc/nginx/* "${nginx_layer_dir}"
+cp -r /opt/drycc/nginx/conf/* "${nginx_layer_dir}"
 cp "${bp_dir}/config/nginx/base.conf" "${nginx_layer_dir}/nginx-php.conf.tpl"
 cat >"${nginx_layer_dir}.toml" <<EOL
+[types]
 cache = true
 build = true
 launch = true
@@ -147,6 +120,7 @@ sed -i "s|@PORT@|\$2|g" "${nginx_layer_dir}/nginx-php.conf"
 php-fpm -c "${php_layer_dir}/config/php.ini" -y "${php_layer_dir}/config/php-fpm.conf" -p "${php_layer_dir}"
 nginx -p "${nginx_layer_dir}" -c "${nginx_layer_dir}/nginx-php.conf"
 SH
+
 chmod +x "${php_layer_dir}/bin/php-nginx-fpm"
 
 generate-launch.sh "${layers_dir}"
diff --git a/buildpacks/python/bin/build b/buildpacks/python/bin/build
--- a/buildpacks/python/bin/build
+++ b/buildpacks/python/bin/build
@@ -1,6 +1,4 @@
 #!/usr/bin/env bash
-# shellcheck source=/dev/null
-. generate-layer.sh
 set -eo pipefail
 
 echo "---> Python Buildpack"
@@ -8,49 +6,21 @@ echo "---> Python Buildpack"
 # 1. GET ARGS
 layers_dir=$1
 plan_path=$3
-arch=$(dpkg --print-architecture) # amd64 arm64
-# 2. DOWNLOAD PYTHON
-python_layer_dir="${layers_dir}/python"
-mkdir -p "${python_layer_dir}"
 
-# determine python version provided during detection
-python_version=$(yj <"${plan_path}" -t | jq -r '.entries[] | select(.name == "python") | .version')
-remote_python_version="not found"
-if [[ -f "${python_layer_dir}.toml" ]]; then
-  remote_python_version=$(yj <"${python_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
-fi
+rm -rf /opt/drycc; ln -s "${layers_dir}" /opt/drycc
 
-if [[ "${python_version}" == "${remote_python_version}" ]]; then
-  echo "---> Reusing python"
-else
-  echo "---> Downloading and extracting Python ${python_version}"
-  python_url="https://buildpacks.drycc.cc/python/${CNB_STACK_ID}/python-${python_version}-${arch}.tar.gz"
-  wget -q -O - "${python_url}" | tar -xzf - -C "${python_layer_dir}"
-  cat >"${python_layer_dir}.toml" <<EOL
-cache = true
-build = true
-launch = true
-metadata = "${python_version}"
-EOL
-  # shellcheck disable=SC2006
-  for file in $( (ls "${python_layer_dir}/bin/")); do
-    if [ "${file}" == 'pip' ]; then
-      sed -ir 's/\#\!\/usr\/local\/bin\/python/\#\!\/usr\/bin\/env\ python/g' "${python_layer_dir}/bin/${file}"
-    fi
-  done
-  if [ ! -s "${python_layer_dir}/profile.d/python.sh" ]; then
-    mkdir "${python_layer_dir}/profile.d"
-    cat >"${python_layer_dir}/profile.d/python.sh" <<EOL
-export PATH="${python_layer_dir}/bin:${PATH}"
-export C_INCLUDE_PATH="${python_layer_dir}/include:${C_INCLUDE_PATH}"
-export CPLUS_INCLUDE_PATH="${python_layer_dir}/include:${CPLUS_INCLUDE_PATH}"
-export LIBRARY_PATH="${python_layer_dir}/lib:${LIBRARY_PATH}"
-export LD_LIBRARY_PATH="${python_layer_dir}/lib:${LD_LIBRARY_PATH}"
-export PKG_CONFIG_PATH="${python_layer_dir}/lib/pkg-config:${PKG_CONFIG_PATH}"
-EOL
-  fi
-fi
+# 2. Install build deps
+# shellcheck source=/dev/null
+. generate-layers.sh "${layers_dir}"
+generate_deps_layer build-deps
+generate_deps_layer run-deps
 
+# 3. install python
+generate_stack_layer python "${plan_path}" true
+# shellcheck source=/dev/null
+. init-stack
+
+python_layer_dir="${layers_dir}"/python
 rm -f "${python_layer_dir}/profile.d/pip.sh"
 if [ "${PIP_INDEX_URL}" ]; then
   tee >>"${python_layer_dir}/profile.d/pip.sh" <<EOF
@@ -63,16 +33,12 @@ python -m pip  config set global.extra-index-url "${PIP_INDEX_URL}"
 EOF
 fi
 
-# 3. MAKE python and pip AVAILABLE TO THIS SCRIPT
-# shellcheck source=/dev/null
-. "${python_layer_dir}/profile.d/python.sh"
-
 # Compares previous requirements checksum to the current requirements
 requirements_layer_dir="${layers_dir}/requirements"
 local_requirements_checksum=$(sha256sum requirements.txt | cut -d ' ' -f 1 || echo 'not found')
 remote_requirements_checksum='not found'
 if [[ -f "${requirements_layer_dir}.toml" ]]; then
-  remote_requirements_checksum=$(yj <"${requirements_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_requirements_checksum=$(yj <"${requirements_layer_dir}.toml" -t | jq -r .metadata.version 2>/dev/null || echo 'not found')
 fi
 mkdir -p "${requirements_layer_dir}"
 
@@ -93,11 +59,16 @@ elif [[ -f requirements.txt ]]; then
     --exists-action=w --src="${python_layer_dir}"/src \
     --disable-pip-version-check --no-cache-dir
   cat >"${requirements_layer_dir}.toml" <<EOL
+[types]
 cache = true
 build = true
 launch = true
-metadata = "${local_requirements_checksum}"
+
+[metadata]
+version = "${local_requirements_checksum}"
 EOL
+  scanelp "${python_layer_dir}" > .auto-deps
+  generate_deps_layer auto-deps
 fi
 
 generate-launch.sh "${layers_dir}"
diff --git a/buildpacks/ruby/bin/build b/buildpacks/ruby/bin/build
--- a/buildpacks/ruby/bin/build
+++ b/buildpacks/ruby/bin/build
@@ -1,72 +1,30 @@
 #!/usr/bin/env bash
-# shellcheck source=/dev/null
-. generate-layer.sh
 set -eo pipefail
 
 echo "---> Ruby Buildpack"
-
 # 1. GET ARGS
 layers_dir=$1
 plan_path=$3
 
-# 2. DOWNLOAD RUBY
-ruby_layer_dir="${layers_dir}/ruby"
-mkdir -p "${ruby_layer_dir}"
-arch=$(dpkg --print-architecture) # amd64 arm64
-ruby_arch=$(uname -m)             # x86_64 aarch64
+rm -rf /opt/drycc; ln -s "${layers_dir}" /opt/drycc
 
-# determine ruby version provided during detection
-ruby_version=$(yj <"${plan_path}" -t | jq -r '.entries[] | select(.name == "ruby") | .version')
-bin_version=${ruby_version:0:4}0
-remote_ruby_version="not found"
-if [[ -f "${ruby_layer_dir}.toml" ]]; then
-  remote_ruby_version=$(yj <"${ruby_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
-fi
-if [[ "${ruby_version}" == "${remote_ruby_version}" ]]; then
-  echo "---> Reusing ruby"
-else
-  echo "---> Downloading and extracting Ruby ${ruby_version}"
-  ruby_url="https://buildpacks.drycc.cc/ruby/${CNB_STACK_ID}/ruby-${ruby_version}-${arch}.tar.gz"
-  wget -q -O - "${ruby_url}" | tar -xzf - -C "${ruby_layer_dir}"
-  cat >"${ruby_layer_dir}.toml" <<EOL
-cache = true
-build = true
-launch = true
-metadata = "${ruby_version}"
-EOL
-  # shellcheck disable=SC2006
-  for file in $( (ls "${ruby_layer_dir}/bin/")); do
-    if [ "${file}" != 'ruby' ]; then
-      sed -ir 's/\#\!\/usr\/local\/bin\/ruby/\#\!\/usr\/bin\/env\ ruby/g' "${ruby_layer_dir}/bin/${file}"
-    fi
-  done
-
-  if [ ! -s "${ruby_layer_dir}/profile.d/ruby.sh" ]; then
-    mkdir "${ruby_layer_dir}/profile.d"
-    cat >"${ruby_layer_dir}/profile.d/ruby.sh" <<EOL
-export PATH="${ruby_layer_dir}/bin:${PATH}"
-export C_INCLUDE_PATH="${ruby_layer_dir}/include:${C_INCLUDE_PATH}"
-export CPLUS_INCLUDE_PATH="${ruby_layer_dir}/include:${CPLUS_INCLUDE_PATH}"
-export LIBRARY_PATH="${ruby_layer_dir}/lib:${LIBRARY_PATH}"
-export LD_LIBRARY_PATH="${ruby_layer_dir}/lib:${LD_LIBRARY_PATH}"
-export RUBYLIB="${ruby_layer_dir}/lib/ruby/${bin_version}/${ruby_arch}-linux/:${ruby_layer_dir}/lib/ruby/${bin_version}"
-export GEM_PATH="${ruby_layer_dir}/lib/ruby/gems/"
-export GEM_HOME="${ruby_layer_dir}/lib/ruby/gems/"
-export RUBYPATH="${ruby_layer_dir}/bin/"
-EOL
-  fi
-fi
-
-# 3. MAKE RUBY AVAILABLE TO THIS SCRIPT
+# 2. Install build deps
 # shellcheck source=/dev/null
-. "${ruby_layer_dir}/profile.d/ruby.sh"
+. generate-layers.sh "${layers_dir}"
+generate_deps_layer build-deps
+generate_deps_layer run-deps
+
+# 3. install ruby
+generate_stack_layer ruby "${plan_path}" true
+# shellcheck source=/dev/null
+. init-stack
 
 # Compares previous Gemfile.lock checksum to the current Gemfile.lock
 bundler_layer_dir="${layers_dir}/bundler"
 local_bundler_checksum=$(sha256sum Gemfile.lock | cut -d ' ' -f 1 || echo 'not found')
 remote_bundler_checksum="not found"
 if [[ -f "${bundler_layer_dir}.toml" ]]; then
-  remote_bundler_checksum=$(yj <"${bundler_layer_dir}.toml" -t | jq -r .metadata 2>/dev/null || echo 'not found')
+  remote_bundler_checksum=$(yj <"${bundler_layer_dir}.toml" -t | jq -r .metadata.version 2>/dev/null || echo 'not found')
 fi
 
 mkdir -p "${bundler_layer_dir}/bin"
@@ -77,12 +35,17 @@ if [[ -f Gemfile.lock && "${local_bundler_checksum}" == "${remote_bundler_checks
 else
   echo "---> Installing gems"
   cat >"${bundler_layer_dir}.toml" <<EOL
+[types]
 cache = true
 build = true
 launch = true
-metadata = "${local_bundler_checksum}"
+
+[metadata]
+version = "${local_bundler_checksum}"
 EOL
   bundle install
+  scanelp "${bundler_layer_dir}" > .auto-deps
+  generate_deps_layer auto-deps
 fi
 
 generate-launch.sh "${layers_dir}"
